### ISSUE TITLE
build framework not found

### ISSUE THREAD

**Issue by kiahmed** [richardschneider/net-ipfs-mount#2]
got this error , trying to build on windows. Not sure how to fix it. Tried manually adding reference but system only had Microsoft Build Framework 4.0 and it didnt do it . Any idea?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:

Server stack trace: 
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at IInnerWeaver.set_Logger(ILogger value)
   at Processor.ExecuteInOwnAppDomain() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 146
   at Processor.Inner() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 93
   at Processor.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 45
Source:
mscorlib
TargetSite:
Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:	IpfsMount

**Comment by richardschneider** [comment]
I forced a build on appveyor (see https://ci.appveyor.com/project/richardschneider/net-ipfs-mount/build/0.2.1-issue-2.1%2B5.build.44) and it passes.  However, there is some **bitrot** about `SHA3`.  This has been removed from `ipfs-core`.  So I'll update the dependencies and see what happens.

However, I can not reproduce your reported problem.  Which version of Visual Studio are you using?  Initially this was developed with Visual Studio 2014 but is now using VS 2017.

Also, could you check that the following packages are installed with the specific version
- package id="Costura.Fody" version="1.6.2" 
- package id="Fody" version="2.2.0"

**Comment by richardschneider** [comment]
Did not mean to close the issue
